ios/RollbarReactNative.m
When I tried to build master locally there appeared to be a small issue around the logWithLevel. 
Thank you for the fantastic product and bringing support to react native.
My Testing:
* Building within a react native app and performing basic logging
=> Fixing a compile error around sending data using logWithLevel

src/Rollbar.js
Allow configuring `reportLevel` to avoid logging more verbose messages.
My Testing:
* Making sure rollbar.com does not include messages lower than my `reportLevel`
=> Allow configuring reportLevel

android/build.gradle
With version `compileSdkVersion 23`, I'm having this error https://stackoverflow.com/questions/49331411/errorresource-androidstyle-textappearance-material-widget-button-borderless-co?rq=1 
The solution for me was to update `compileSdkVersion` to 26
=> Be able to change compileSdkVersion and buildToolsVersion

.gitignore, android/build.gradle
* To be compatible with Gradle version 4.6 and the Android Gradle
plugin version 3.2.1, the build.gradle file must be updated.
* Fix a deprecation warning by renaming `compile` => `implementation`.
Resolves: https://github.com/rollbar/rollbar-react-native/issues/59
=> Update Gradle Build

ios/RollbarReactNative.m, package.json, react-native.config.js
Several unrelated compatibility fixes:
Fixes: 
* https://github.com/rollbar/rollbar-react-native/issues/78
* https://github.com/rollbar/rollbar-react-native/issues/80
* https://github.com/rollbar/rollbar-react-native/issues/81
Note:
rnpm cofig is left in place to ensure compatibility with older react-native CLI. It wasn't clear to me  when react-native.config.js was fully supported, as there was a large refactor Apr 1, 2019. (https://github.com/react-native-community/cli/pull/254) Or perhaps that was when it was first supported. When react-native.config.js is used, rnpm is ignored and there are no warnings.
=> Compatibility fixes

ios/RollbarReactNative.h, ios/RollbarReactNative.m
- use_framework! is necessary for certain swift libraries and it makes certain header incompatible
- to fix that, use the same __has_include used for RCTBridgeModule on all the other imports
- tested on a fresh project without use_framework and a more involved project containing use_framework
- related https://github.com/facebook/react-native/pull/25393/files and https://github.com/facebook/react-native/issues/25349
=> fix: build with use_framework within CocoaPods

android/build.gradle, android/src/main/java/com/rollbar/RollbarReactNative.java, ios/RollbarReactNative.m, src/Rollbar.js, src/merge.js
Partially addresses https://github.com/rollbar/rollbar-react-native/issues/79
Adds device information attributes to the payload client key for Rollbar events in the Javascript domain. This PR only addresses static information that can be fetched once at init time. (e.g. Device ID, Model, etc.) Other dynamic properties (memory, capacity, etc.) will be addressed in a later PR.
=> Send device attributes in payload client key

src/Rollbar.js
Enables some missing options from rollbar.js, and uses `undefined` as the default where possible, so the diagnostic info for user options better reflects what was set by the user and also allows rollbarjs to control the default.
=> Enable some existing rollbar.js options

android/build.gradle
The Android app store currently requires targetSdkVersion >= 26. This PR bumps it to 27 to match the current rollbar-java/android setting.
=> Update targetSdkVersion to > 26 as required by android app store

android/build.gradle
Fixes: https://github.com/rollbar/rollbar-react-native/issues/104, https://github.com/rollbar/rollbar-react-native/issues/112
Enables uncaught exception capture in the native android environment by pulling in https://github.com/rollbar/rollbar-java/pull/200.
This also pulls in all rollbar-android updates since 1.4.0: https://github.com/rollbar/rollbar-java/releases
=> Update rollbar-android v1.7.1

android/src/main/java/com/rollbar/RollbarReactNative.java
Fixes: https://github.com/rollbar/rollbar-react-native/issues/106
To enable Proguard support, allows setting the code version in AndroidManifest.xml:
```
<application>
<meta-data android:name="com.rollbar.android.CODE_VERSION" android:value="1.0.0" />
</application>
```
https://github.com/rollbar/rollbar-react-native/issues/106 suggests adding to the arguments for `init()`, but this doesn't scale well as more config options are needed in the future, and method overloading for `init()` is unmanageable when all the args are the same type (String).
=> Allow setting the code version for android

package.json
Fixes: https://github.com/rollbar/rollbar-react-native/issues/109
Picks up https://github.com/rollbar/rollbar.js/pull/847
More generally, picks up Rollbar.js updates since 2.14.0: (https://github.com/rollbar/rollbar.js/releases)
* Allow callbacks (`onSendCallback`, `CheckIgnore`, `transform`) in react-native target
* Only build stack for http errors when the feature is enabled
* Fixes wrong byte count for truncation
* Allow rollbar errors on xhr/fetch http status (4xx/5xx/0)
* Correctly parse method names with parens in stack traces
* gracefully handle loadFull being called multiple times
* Add CodePush Rewrite Rule
* Enable new CDN
=> Update rollbar.js 2.16.1

src/Rollbar.js
Fixes: https://github.com/rollbar/rollbar-react-native/issues/101
The Android Chrome debugger throws an error when this option is enabled, because the debugger disallows synchronous native calls. Disable by default, and people who want the metadata can enable it.
=> Set captureDeviceInfo false by default

src/Rollbar.js
Fixes: https://github.com/rollbar/rollbar-react-native/issues/74
This PR allows running the JS Rollbar client without the `NativeClient` native binding. For unejected Expo apps, or any other JS only React Native app, just npm/yarn install and add to your project:
```
import { Client, Configuration } from 'rollbar-react-native'
const config = new Configuration('POST_CLIENT_ITEM_ACCESS_TOKEN', {
logLevel: 'info'
});
const rollbar = new Client(config);
```
This no longer throws when the native binding is missing, and omits the message about `react-native link`. Since RN 0.60, `react-native link` is no longer used (native dependencies are autolinked), so this should be fine. Especially since JS-only apps are becoming more common.
I first looked at whether Expo apps could just import the …
=> Enable js-only Expo (no native linking required)

android/src/main/java/com/rollbar/RollbarReactNative.java
Some developers would like to handle native crash with a different handler than rollbar. This option is already present in the native sdk.
=> Allow passing registerExceptionHandler parameter

package.json
Sets minimum version of Rollbar.js to pick up JSON polyfill fix - https://github.com/rollbar/rollbar.js/releases/tag/v2.19.3.
Fixes: ch72255
**N/A: rollbar-react-native doesn't have test automation. The change has been tested manually.**
=> Update rollbar.js to 2.19.3

RollbarReactNative.podspec
Latest Xcode 12 fails to build if the module doesn't depend on React-Core. Please check the following link for me details: [facebook/react-native#29633](https://github.com/facebook/react-native/issues/29633#issuecomment-694187116)
[facebook/react-native#29633](https://github.com/facebook/react-native/issues/29633#issuecomment-694187116)
=> Fix React depenedency to enable XCode 12 build

index.d.ts
Add missing `captureDeviceInfo` property to type definitions file
https://github.com/rollbar/rollbar-react-native/issues/142
> Fix [#1]()
=> Add missing `captureDeviceInfo` property to type definitions file

ios/RollbarReactNative.m
Update export method to expect `NSNull` or `NSString`. This wasn't a problem in the 0.x builds, but it is definitely failing now when setting any of these keys to null.
Tested manually.
Fixes https://app.shortcut.com/rollbar/story/121821/
=> handle NSNull in json argument

.gitmodules, RollbarReactNative.podspec, ios/RollbarReactNative.h, ios/RollbarReactNative.m, ios/RollbarReactNative.xcodeproj/project.pbxproj, ios/RollbarReactNative.xcworkspace/contents.xcworkspacedata
Replaces rollbar-ios with rollbar-apple for iOS native support.
Note: This PR contains breaking changes and merges to the 1.0 rc PR, https://github.com/rollbar/rollbar-react-native/pull/169.
Fixes: 
* https://app.shortcut.com/rollbar/story/123418/
* https://github.com/rollbar/rollbar-react-native/issues/173
=> Replace rollbar-ios with rollbar-apple

ios/RollbarReactNative.m
When making changes to the configuration (setting access token, changing user etc), a non-mutable config is used.
This change calls `mutableCopy` on the RollbarConfig instead of just casting it to a RollbarMutableConfig.
- Bug fix (non-breaking change that fixes an issue)
- #178
=> Fix for mutable config

RollbarReactNative.podspec
The latest React-Core dependency used by the SDK has upped its ios minimum deployment version to 13.0. This is probably due to Apple dropping older versions of the os.
Without this, the podspec will fail to lint.
=> Bumped minimum deployment to 13 tracking React-Core dep minimum

RollbarReactNative.podspec
This PR updates the SDK to use the latest Rollbar Apple SDK 3.3.1 which fixes a compilation issue with Xcode 16 beta.
- Fix [SDK-365](https://linear.app/rollbar-inc/issue/SDK-365/rollbar-wont-compile-for-a-swift-mac-os-app)
=> Use latest Rollbar Apple SDK 3.3.1

RollbarReactNative.podspec
This PR updates the SDK to use the latest Rollbar Apple SDK 3.3.2 which fixes more compilation issues with Xcode 16 beta.
- Fix https://github.com/rollbar/rollbar-react-native/issues/195
=> Use latest Rollbar Apple SDK 3.3.2
